server:
  port: 8082
spring:
  datasource:
    password: Tiger2143@+%
    url: jdbc:mysql://localhost:3306/task_project
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
